### ISSUE TITLE
Update for Itunes12

### ISSUE THREAD

**Issue by shiprec** [aaronfreimark/Apple-ID-AppleScript#29]
Hello @aaronfreimark i know it has been a while since this project has been updated.  I was wondering if you knew of anyone who was able to get this working with the current version of Itunes?

Thank you for the help!

**Comment by aaronfreimark** [comment]
Hey there. Sorry, I don't think this has been possible for several years.

**Comment by shiprec** [comment]
Ok thank you for the quick response!
